# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Frenetic LLC Blog

# it will display as the sub-title
tagline: From the software development team at Frenetic LLC.

email: team@freneticllc.com

description: >-
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.

social:
    name: Frenetic LLC
    email: team@freneticllc.com
    links:
        - https://freneticllc.com
        - https://github.com/FreneticLLC

twitter_username: freneticllc
github_username: freneticllc

avatar: /assets/img/frenetic-512.png

lang: en
timezone: America/Los_Angeles

# the base hostname & protocol for your site, e.g. http://example.com
url: ""

# the subpath of your site, e.g. /blog
baseurl: ""

# boolean type, the global switch for TOC in posts.
toc: true

# Build settings
theme: jekyll-theme-chirpy
plugins:
    - jekyll-feed

assets:
    self_host:
        # TODO: The self-host package is missing bootstrap/jquery so it breaks? wtf?
        # swap to 'true' when that's fixed
        enabled: false

kramdown:
    hard_wrap: true
    footnote_backlink: "&#8617;&#xfe0e;"
    syntax_highlighter: rouge
    syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
        css_class: highlight
        # default_lang: console
        span:
            line_numbers: false
        block:
            line_numbers: true
        start_line: 1

collections:
    tabs:
        output: true
        sort_by: order

defaults:
    - scope:
        path: "" # An empty string here means all files in the project
        type: posts
      values:
        layout: post
        comments: true # Enable comments in posts.
        toc: true # Display TOC column in posts.
        # DO NOT modify the following parameter unless you are confident enough
        # to update the code of all other post links in this project.
        permalink: /posts/:title/
    - scope:
        path: _drafts
      values:
        comments: false
    - scope:
        path: ""
        type: tabs # see `site.collections`
      values:
        layout: page
        permalink: /:title/
    - scope:
        path: assets/js/dist
      values:
        swcache: true

sass:
    style: compressed

compress_html:
    clippings: all
    comments: all
    endings: all
    profile: false
    blanklines: false
    ignore:
        envs: [development]

exclude:
    - "*.gem"
    - "*.gemspec"
    - docs
    - tools
    - README.md
    - LICENSE
    - "*.config.js"
    - package*.json

jekyll-archives:
    enabled: [categories, tags]
    layouts:
        category: category
        tag: tag
    permalinks:
        tag: /tags/:name/
        category: /categories/:name/
